# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:52
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import technology.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=300, verbose_name='Кафедра')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('max_rating', models.IntegerField(default=1, verbose_name='Максимальный балд')),
                ('variant', models.IntegerField(default=0, verbose_name='Вариант')),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='technology.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to=technology.models.make_upload_path, verbose_name='Отчет')),
                ('rating', models.IntegerField(blank=True, default=1, null=True, verbose_name='Баллы')),
                ('price', models.CharField(blank=True, choices=[('Не зачет', 'Не зачет'), ('Удволитворительно', 'Удволитворительно'), ('Хорошо', 'Хорошо'), ('Отлично', 'Отлично')], max_length=300, null=True, verbose_name='Оценка')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('laboratory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='technology.Laboratory', verbose_name='Отчеты')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField(default=0, verbose_name='Вариант')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.Group', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['-variant'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='technology.UserGroup', verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='technology.Group'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
