# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_create'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AddField(
            model_name='report',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
